[telegram]
bot_name = "ultimate_pollbot"
bot_token = ""
api_id = 0
api_hash = ""
admin = "Nukesor"
max_shared_per_poll = 20
allow_private_votes = false

[database]
sql_uri = "postgres://localhost/pollbot_test"
connection_count = 20
overflow_count = 10

[logging]
sentry_enabled = false
sentry_token = ""
log_level = 20
debug = true
