[telegram]
bot_name = "your_bots_@_name"
bot_token = "your_telegram_bot_token"
api_id = your_api_id
api_hash = "your_api_hash"
admin = "Your name"
max_shared_per_poll = 20
allow_private_votes = false

[database]
sql_uri = "postgres://localhost/pollbot"
connection_count = 20
overflow_count = 10

[logging]
sentry_enabled = false
sentry_token = ""
log_level = 20
debug = false
